sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t mastaak/alprint .
# push image
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag mastaak/mastaak/alprint:latest mastaak/mastaak/alprint
- docker push mastaak/mastaak/alprint
